version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - photoviewer
    networks:
      - webnet

  photoviewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photoviewer-container
    networks:
      - webnet
    environment:
      - NAS_PATH=${NAS_PATH}  # .envファイルのNAS_PATHを使用

networks:
  webnet:
    driver: bridge
