version: "3.8"

services:
  nginx:
    ports:
      - "8081:81" # 本番用に80ポートで公開
    restart: always # サービスの自動再起動
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

  photoviewer:
    environment:
      - NODE_ENV=production
    volumes:
      - "${HOST_NAS_PATH}:${NAS_PATH}"
    restart: always

