version: '3.8'

services:
  nginx:
    ports:
      - "8080:80"  # 本番用に80ポートで公開
    restart: always  # サービスの自動再起動
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

  remix_app:
    environment:
      - NODE_ENV=production
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}  # .envファイルのBASIC_AUTH_USERNAMEを使用
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}  # .envファイルのBASIC_AUTH_PASSWORDを使用
    ports:
      - "5173:5173"  # 本番環境では内部通信のみで使用
    volumes:
      - "${HOST_NAS_PATH}:${NAS_PATH}"
    restart: always
